TITLE = "Niobium"
INSTAGRAM = "eisenheim_photo"
PHOTOS_DIR = "photos/"
CACHE_DIR = "cache/"
DATABASE_PATH = "niobium.sqlite"
SORT_ORDER = "date_taken,sort_order,filename"
REVERSE_SORT_ORDER = true
DEFAULT_ROW_HEIGHT = 23 # vh
ROW_HEIGHT_STEP = 10 # %
SHOW_DOWNLOAD_BUTTON = true
SLIDESHOW_DELAY = 5000 # ms
THUMBNAIL_MAX_SIZE = 800 # px, on any side
LARGE_VIEW_MAX_SIZE = 1920 # px, on any side
READ_EXIF = true
SHOW_METADATA = true
METADATA_VISIBLE_BY_DEFAULT = true
DOWNLOAD_PREFIX = "niobium_"