TITLE = "Shashin"
INSTAGRAM = "eisenheim_photo"
PHOTOS_DIR = "photos/"
CACHE_DIR = "cache/"
DEFAULT_ROW_HEIGHT = 30 # vh
ROW_HEIGHT_STEP = 10 # %
SLIDESHOW_DELAY = 5000 # ms
THUMBNAIL_MAX_SIZE = 800 # px, on any side
READ_EXIF = true
SHOW_METADATA = true
METADATA_VISIBLE_BY_DEFAULT = true