TITLE = "Niobium"
INSTAGRAM = "eisenheim_photo"
PHOTOS_DIR = "photos"
CACHE_DIR = "cache"
INDEX_SUBDIRS = true
PRE_PARSE_DIMENSIONS = true
SHOW_PHOTOS_FROM_SUBDIRS = true
SHOW_NAVIGATION_PANEL = true
DATABASE_PATH = "niobium.sqlite"
SORT_ORDER = "filename"
REVERSE_SORT_ORDER = false
DEFAULT_ROW_HEIGHT = 23 # vh
MAX_ZOOM = 2
ROW_HEIGHT_STEP = 10 # %
SHOW_DOWNLOAD_BUTTON = true
SLIDESHOW_DELAY = 5000 # ms
THUMBNAIL_MAX_SIZE = 400 # px, on any side
THUMBNAIL_QUALITY = 70 # %
LARGE_VIEW_MAX_SIZE = 1920 # px, on any side
LARGE_VIEW_QUALITY = 85 # %
READ_EXIF = true
SHOW_METADATA = true
METADATA_VISIBLE_BY_DEFAULT = true
DOWNLOAD_PREFIX = "niobium_"
BEHIND_REVERSE_PROXY = true
